mongodb:
  architecture: replicaset
  auth:
    enabled: true
    rootPassword: "MyRootPassword123"
    username: "admin"
    password: "admin123"
    database: "excel_db"
  persistence:
    size: 8Gi
    storageClass: "ebs-csi-gp3"

