mongodb:
  architecture: replicaset
  auth:
    enabled: true
    rootPassword: "MyRootPassword123"  
    username: ""                         
    password: ""                         
    database: ""                         
  persistence:
    size: 8Gi
    storageClass: "ebs-csi-gp3"
