replicaCount: 2

image:
  repository: 884394270539.dkr.ecr.ap-south-1.amazonaws.com/development/excel_uploader
  tag: v1.0.4
  pullPolicy: IfNotPresent

service:
  type: ClusterIP
  port: 5000

resources: {}

env:
  MONGO_HOST: "portfolio-umbrella-mongodb-headless"
  MONGO_PORT: 27017
  ROOT_USERNAME: "root"
  ROOT_PASSWORD: "MyRootPassword123"
  MONGO_DB: "excel_db"

ingress:
  enabled: true
  ingressClassName: nginx
  hosts:
    - host: "" 
      paths:
        - path: /
          pathType: Prefix

livenessProbe:
  httpGet:
    path: /health
    port: 5000
  initialDelaySeconds: 30
  periodSeconds: 10

readinessProbe:
  httpGet:
    path: /health
    port: 5000
  initialDelaySeconds: 10
  periodSeconds: 5
