apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ include "flask-app.fullname" . }}-ingress
spec:
  ingressClassName: nginx
  rules:
    - host: myportfolio.dbloader.com
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: {{ include "flask-app.fullname" . }}
                port:
                  number: {{ .Values.service.port }}


